# Generated by Django 3.0 on 2020-11-23 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='decision',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='input',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='output',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='technologie',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts_act', to='classroom.Partner', verbose_name='Select Your University  '),
        ),
        migrations.AlterField(
            model_name='decision',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts_dec', to='classroom.Partner', verbose_name='Select Your University  '),
        ),
        migrations.AlterField(
            model_name='decision',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_process', to='classroom.Task', verbose_name='Task Decision '),
        ),
        migrations.AlterField(
            model_name='input',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts_input', to='classroom.Partner', verbose_name='Select Your University  '),
        ),
        migrations.AlterField(
            model_name='output',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts_out', to='classroom.Partner', verbose_name='Select Your University  '),
        ),
        migrations.AlterField(
            model_name='output',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='output_process', to='classroom.Task', verbose_name='Task Output '),
        ),
        migrations.AlterField(
            model_name='skill',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts_skill', to='classroom.Partner', verbose_name='Select Your University  '),
        ),
        migrations.AlterField(
            model_name='skill',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_process', to='classroom.Task', verbose_name='Task  '),
        ),
        migrations.AlterField(
            model_name='technologie',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts_tech', to='classroom.Partner', verbose_name='Select Your University  '),
        ),
        migrations.AlterField(
            model_name='technologie',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tech_process', to='classroom.Task', verbose_name='Task '),
        ),
    ]
